name: Run Test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java_version: 17
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x

      - name: Run Unit Tests
        run: ./gradlew clean testDebug



