name: AndroidBuild
on:
  pull_request:
    branches: [ main, develop, feature/* ]
  push:
    branches: [ main, develop, feature/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: android-ci-cd.apk
          path: app/build/outputs/apk/app-debug.apk



